# fly.toml app configuration file generated for poseidon-mqtt-broker on 2024-06-25T12:13:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poseidon-mqtt-broker'
primary_region = 'ams'

[build]

[[services]]
  internal_port = 1883
  protocol = "tcp"

[[services]]
  internal_port = 9001
  protocol = "tcp"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
