// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/consumer_test_answers": {
            "get": {
                "description": "Get all consumer test answers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_answers"
                ],
                "summary": "Show all consumer test answers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.ConsumerTestAnswer"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing consumer test answer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_answers"
                ],
                "summary": "Update a consumer test answer",
                "parameters": [
                    {
                        "description": "Consumer Test Answer",
                        "name": "answer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestAnswer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestAnswer"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new consumer test answer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_answers"
                ],
                "summary": "Create a consumer test answer",
                "parameters": [
                    {
                        "description": "Consumer Test Answer",
                        "name": "answer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestAnswer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestAnswer"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing consumer test answer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_answers"
                ],
                "summary": "Delete a consumer test answer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Consumer Test Answer ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/consumer_test_questions": {
            "get": {
                "description": "Get all consumer test questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_questions"
                ],
                "summary": "Show all consumer test questions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.ConsumerTestQuestion"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing consumer test question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_questions"
                ],
                "summary": "Update a consumer test question",
                "parameters": [
                    {
                        "description": "Consumer Test Question",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestQuestion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestQuestion"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new consumer test question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_questions"
                ],
                "summary": "Create a consumer test question",
                "parameters": [
                    {
                        "description": "Consumer Test Question",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestQuestion"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTestQuestion"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing consumer test question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_test_questions"
                ],
                "summary": "Delete a consumer test question",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Consumer Test Question ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/consumer_tests": {
            "get": {
                "description": "Get all consumer tests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_tests"
                ],
                "summary": "Show all consumer tests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.ConsumerTest"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing consumer test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_tests"
                ],
                "summary": "Update a consumer test",
                "parameters": [
                    {
                        "description": "Consumer Test",
                        "name": "test",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTest"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new consumer test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_tests"
                ],
                "summary": "Create a consumer test",
                "parameters": [
                    {
                        "description": "Consumer Test",
                        "name": "test",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.ConsumerTest"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing consumer test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumer_tests"
                ],
                "summary": "Delete a consumer test",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Consumer Test ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/likes": {
            "get": {
                "description": "Get all likes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "likes"
                ],
                "summary": "Show all likes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Like"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing like",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "likes"
                ],
                "summary": "Update a like",
                "parameters": [
                    {
                        "description": "Like",
                        "name": "like",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.Like"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Like"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new like",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "likes"
                ],
                "summary": "Create a like",
                "parameters": [
                    {
                        "description": "Like",
                        "name": "like",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.Like"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.Like"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing like",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "likes"
                ],
                "summary": "Delete a like",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Like ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/nfchips": {
            "get": {
                "description": "Get all NFC chips",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nfchips"
                ],
                "summary": "Show all NFC chips",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.NFCChip"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing NFC chip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nfchips"
                ],
                "summary": "Update an NFC chip",
                "parameters": [
                    {
                        "description": "NFC Chip",
                        "name": "chip",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.NFCChip"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.NFCChip"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new NFC chip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nfchips"
                ],
                "summary": "Create an NFC chip",
                "parameters": [
                    {
                        "description": "NFC Chip",
                        "name": "chip",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.NFCChip"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.NFCChip"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing NFC chip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nfchips"
                ],
                "summary": "Delete an NFC chip",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NFC Chip ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/refill_station_problems": {
            "get": {
                "description": "Get all refill station problems",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_problems"
                ],
                "summary": "Show all refill station problems",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.RefillStationProblem"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing refill station problem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_problems"
                ],
                "summary": "Update a refill station problem",
                "parameters": [
                    {
                        "description": "Refill Station Problem",
                        "name": "problem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationProblem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationProblem"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new refill station problem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_problems"
                ],
                "summary": "Create a refill station problem",
                "parameters": [
                    {
                        "description": "Refill Station Problem",
                        "name": "problem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationProblem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationProblem"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing refill station problem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_problems"
                ],
                "summary": "Delete a refill station problem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Refill Station Problem ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/refill_station_reviews": {
            "get": {
                "description": "Get all refill station reviews",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_reviews"
                ],
                "summary": "Show all refill station reviews",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.RefillStationReview"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing refill station review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_reviews"
                ],
                "summary": "Update a refill station review",
                "parameters": [
                    {
                        "description": "Refill Station Review",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationReview"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new refill station review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_reviews"
                ],
                "summary": "Create a refill station review",
                "parameters": [
                    {
                        "description": "Refill Station Review",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationReview"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStationReview"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing refill station review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_station_reviews"
                ],
                "summary": "Delete a refill station review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Refill Station Review ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/refill_stations": {
            "get": {
                "description": "Get all refill stations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_stations"
                ],
                "summary": "Show all refill stations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.RefillStation"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing refill station",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_stations"
                ],
                "summary": "Update a refill station",
                "parameters": [
                    {
                        "description": "Refill Station",
                        "name": "station",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStation"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new refill station",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_stations"
                ],
                "summary": "Create a refill station",
                "parameters": [
                    {
                        "description": "Refill Station",
                        "name": "station",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.RefillStation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.RefillStation"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing refill station",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refill_stations"
                ],
                "summary": "Delete a refill station",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Refill Station ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Show all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.User"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.User"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.User"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/water_transactions": {
            "get": {
                "description": "Get all water transactions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "water_transactions"
                ],
                "summary": "Show all water transactions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.WaterTransaction"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing water transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "water_transactions"
                ],
                "summary": "Update a water transaction",
                "parameters": [
                    {
                        "description": "Water Transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.WaterTransaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.WaterTransaction"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new water transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "water_transactions"
                ],
                "summary": "Create a water transaction",
                "parameters": [
                    {
                        "description": "Water Transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.WaterTransaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/database.WaterTransaction"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing water transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "water_transactions"
                ],
                "summary": "Delete a water transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Water Transaction ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "database.ConsumerTest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.ConsumerTestQuestion"
                    }
                }
            }
        },
        "database.ConsumerTestAnswer": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "questionID": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "database.ConsumerTestQuestion": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.ConsumerTestAnswer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "maxValue": {
                    "type": "number"
                },
                "minValue": {
                    "type": "number"
                },
                "testID": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "database.Like": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "likes": {
                    "type": "boolean"
                },
                "stationID": {
                    "type": "integer"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "database.NFCChip": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "fillVolume": {
                    "type": "integer"
                },
                "hardwareID": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pathImage": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "waterTransactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.WaterTransaction"
                    }
                },
                "waterType": {
                    "type": "string"
                }
            }
        },
        "database.RefillStation": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imagePath": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "likeCounter": {
                    "type": "integer"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Like"
                    }
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "offeredWaterTypes": {
                    "type": "string"
                },
                "openingTimes": {
                    "type": "string"
                },
                "problems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.RefillStationProblem"
                    }
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.RefillStationReview"
                    }
                },
                "type": {
                    "type": "string"
                },
                "waterSource": {
                    "type": "string"
                },
                "waterTransactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.WaterTransaction"
                    }
                }
            }
        },
        "database.RefillStationProblem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "linkToMedia": {
                    "type": "string"
                },
                "stationID": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "database.RefillStationReview": {
            "type": "object",
            "properties": {
                "accessibility": {
                    "type": "integer"
                },
                "cleanness": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "stationID": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "waterQuality": {
                    "type": "integer"
                }
            }
        },
        "database.User": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.ConsumerTestAnswer"
                    }
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Like"
                    }
                },
                "nfcchips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.NFCChip"
                    }
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.RefillStationReview"
                    }
                }
            }
        },
        "database.WaterTransaction": {
            "type": "object",
            "properties": {
                "chipID": {
                    "type": "integer"
                },
                "guest": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "stationID": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                },
                "waterType": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server for a water station.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
