# .github/workflows/cloud-run.yml

name: Cloud Run Deployment

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: Poseidon-Backend
  REGION: europe-central2
  DOCKER_IMAGE: Poseidon_Backend

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Set up Google Cloud SDK
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      # Configure Docker
      - name: Configure docker for GCP
        run: gcloud auth configure-docker  
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            HTTP_PORT=8080
    
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE }}:latest
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap