name: Main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: Poseidon-Backend # google run service name
  REGION: europe-central2

on: # When do you want it to run
  push: # When pushed to master branch 
    branches:
        - main

jobs: # Define jobs to run

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Sets up the gcloud cli with the credentials we previously created, and will be storing within Github as secrets.
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

        # Configure Docker with Credentials
      - name: Authorize Docker push
        run: gcloud auth configure-docker

        # Build the Go binary
      - name: Build Go binary
        run: go build -o app .

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/my-image .
          docker push gcr.io/${{ env.PROJECT_ID }}/my-image
      
      # Deploy the container image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} --image gcr.io/${{ env.PROJECT_ID }}/my-image --platform managed --region ${{ env.REGION }}